# Generated by Django 6.0.5 on 2026-06-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='stock_status',
        ),
    ]
