# Generated by Django 6.0.5 on 2026-06-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_remove_ingredient_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='Stock_Status',
            field=models.BooleanField(default=False),
        ),
    ]
