# Generated by Django 6.0.5 on 2026-06-04 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_ingredient_stock_status'),
        ('recipe', '0005_alter_recipe_date_to_cook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='Stock_Status',
            new_name='stock_status',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipeid',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.recipe'),
            preserve_default=False,
        ),
    ]
