# Generated by Django 6.0.5 on 2026-06-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_rename_stock_status_ingredient_stock_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='stock_status',
        ),
    ]
