# Generated by Django 6.0.5 on 2026-06-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_remove_ingredient_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='stock_status',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
