# Generated by Django 6.0.5 on 2026-06-05 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_ingredient_stock_status'),
        ('recipe', '0010_remove_recipe_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recipeid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.recipe'),
        ),
    ]
