# Generated by Django 6.0.5 on 2026-06-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_alter_ingredient_recipeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams (g)'), ('kg', 'Kilograms (kg)'), ('ml', 'Milliliters (ml)'), ('l', 'Liters (l)'), ('pcs', 'Pieces (pcs)'), ('tbsp', 'Tablespoon (tbsp)'), ('tsp', 'Teaspoon (tsp)'), ('cup', 'Cup (cup)')], default='pcs', max_length=10),
        ),
    ]
