# Generated by Django 6.0.5 on 2026-05-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('steps_to_cook', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
    ]
