# Generated by Django 6.0.5 on 2026-06-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('DESSERT', 'Dessert'), ('SNACK', 'Snack')], default='SNACK', max_length=10),
        ),
    ]
