# Generated by Django 6.0.5 on 2026-06-03 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_to_cook',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
