# Generated by Django 6.0.5 on 2026-06-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_recipe_date_to_cook'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='steps_to_cook',
            field=models.TextField(blank=True),
        ),
    ]
