# Generated by Django 6.0.5 on 2026-06-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_recipe_steps_to_cook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='available',
        ),
    ]
