# Generated by Django 6.0.5 on 2026-06-05 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_remove_recipe_accountid_recipe_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='account',
        ),
    ]
