# Generated by Django 6.0.5 on 2026-06-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingtransaction',
            name='cooking_completed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cookingtransaction',
            name='rating',
            field=models.CharField(max_length=100),
        ),
    ]
