# Generated by Django 6.0.5 on 2026-06-03 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_transaction', '0002_alter_cookingtransaction_cooking_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingtransaction',
            name='date_cooked',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cookingtransaction',
            name='cooking_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cookingtransaction',
            name='rating',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆ (Poor)'), (2, '★★☆☆☆ (Fair)'), (3, '★★★☆☆ (Good)'), (4, '★★★★☆ (Very Good)'), (5, '★★★★★ (Excellent)')], default=5),
        ),
    ]
