# Generated by Django 6.0.5 on 2026-06-04 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_transaction', '0003_cookingtransaction_date_cooked_and_more'),
        ('recipe', '0007_remove_recipe_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingtransaction',
            name='recipeid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cooking_transactions', to='recipe.recipe'),
            preserve_default=False,
        ),
    ]
