# Generated by Django 6.0.5 on 2026-06-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_transaction', '0004_cookingtransaction_recipeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookingtransaction',
            name='cooking_completed',
        ),
        migrations.RemoveField(
            model_name='cookingtransaction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cookingtransaction',
            name='rating',
        ),
    ]
