# Generated by Django 6.0.5 on 2026-06-05 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_transaction', '0005_remove_cookingtransaction_cooking_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingtransaction',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
